apiVersion: v1
kind: Service
metadata:
  name: CCNN-frontend
  namespace: CCNN
  labels:
    app: CCNN-frontend
spec:
  selector:
    app: CCNN-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
