apiVersion: v1
kind: Service
metadata:
  name: cybertwin-OIDC-service
  namespace: cybertwin
  labels:
    app: cybertwin-OIDC-service
spec:
  type: ClusterIP
  selector:
    app: cybertwin-OIDC-service
  ports:
    - name: http
      port: 31111
      targetPort: 5000
      protocol: TCP
